v0.0.1: Added dep_check for jq + More sensible logging

diff --git a/ipfs-link b/ipfs-link
--- a/ipfs-link
+++ b/ipfs-link
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
+# Info: See `usage` funtion below
 
-export version=0.0.0 IPFS_PATH="${IPFS_PATH:="${HOME}"/.ipfs}"
+export version=0.0.1 IPFS_PATH="${IPFS_PATH:="${HOME}"/.ipfs}"
 
 usage(){
   echo -e '\nBrief: Announce dynamic multiaddress of isolated or private node through IPNS or get multiaddress to such a node'
@@ -19,6 +20,19 @@ usage(){
   echo -e '\nExamples & Details: https://github.com/SomajitDey/ipfs-link'
   exit
 } >&2; export -f usage
+
+dep_check(){
+  # Brief: Check major dependencies
+  local quit
+  if ! command -v jq &>/dev/null; then
+    echo -e "Required: jq\nSource: Native package repository"
+    echo -e "Ref: https://stedolan.github.io/jq/download/\n"
+    quit="yes"
+  fi
+  [[ -v quit ]] && exit 1
+} >&2; export -f dep_check
+
+dep_check
 
 keygen(){
   # Brief: Generate swarm key on stdout according to keygen_mode
@@ -61,7 +75,6 @@ parse_cmdline "${@}"
 
 main_node_config(){
   # Brief: Config the isolated / private node if not already online
-  export main_node_ID="$(ipfs id -f='<id>')"
   ipfs swarm peers && return 0
   [[ -v keygen_mode ]] && keygen > "${IPFS_PATH}"/swarm.key
   if [[ -f "${IPFS_PATH}"/swarm.key ]]; then # Remove default bootstrap nodes in presence of swarm key
@@ -77,8 +90,10 @@ main_node_config(){
   [[ "$(ipfs daemon "${daemon_opts[@]}" | grep -iom1 'Daemon is ready' & tail -f --pid=$! /dev/null)" ]]
 } &>/dev/null; export main_node_config
 
+export main_node_ID="$(ipfs id -f='<id>')"
+echo -e "Status: Getting node online...\nID: ${main_node_ID}\nRepo: ${IPFS_PATH}"
 if main_node_config; then
-  echo -e "Status: Node is online\nID: ${main_node_ID}\nRepo: ${IPFS_PATH}"
+  echo -e "Status: Node is online"
   [[ -f "${IPFS_PATH}"/swarm.key ]] && echo -e "Swarm key file: ${IPFS_PATH}/swarm.key\n" || echo
   [[ "$(ipfs name pubsub state)" == enabled ]] || \
     { echo "Error: IPNS over pubsub not enabled. Run your ipfs daemon with --enable-namesys-pubsub"; exit 1;}
